# Generated by Django 3.2.6 on 2021-08-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='datetime',
            field=models.DateTimeField(verbose_name='%d-%m-%%H:%M:%S'),
        ),
    ]
