# Generated by Django 3.2.6 on 2021-08-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question1', '0004_alter_navigationrecord_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
